b_verbose: false

odom_pub_rate: 10

# How long to wait for transform between timestamps
transform_wait_duration: 0.01

translation_threshold_kf: 1.0
rotation_threshold_kf: 0.3

number_of_points_open_space: 9999999 # Disabled - baseline to use is: 11000

map_publishment:
  b_publish_map: true
  meters: 1

queues:
  lidar_queue_size: 1
  imu_queue_size: 100
  odom_queue_size: 100

buffers:
  imu_buffer_size_limit: 100
  odometry_buffer_size_limit: 100

# DATA INTEGRATION 
  # 0   ---> no integration 
  # 1   ---> imu integration 
  # 2   ---> imu yaw integration
  # 3   ---> odometry integration 

data_integration:
  mode: 3

b_is_flat_ground_assumption: false

b_enable_computation_time_profiling: true

b_run_with_gt_point_cloud: false
gt_point_cloud_filename: /home/costar/data/loeval/beta_both_floors.pcd

publish_diagnostics: false

# SLIDING WINDOW PARAMETERS

b_enable_msw: true

# Options
  # mapper -> PointCloudMapper
  # multi_threaded_mapper -> PointCloudMultiThreadedMapper
  # ikdtree_mapper -> PointCloudIkdTreeMapper

window_local_mapping_type: multi_threaded_mapper

box_filter_size: 10
velocity_buffer_size: 10
translation_threshold_msw: 5
rotational_velocity_threshold: 1
translational_velocity_threshold: 0.1

# Statistics 

statistics_time_window: 5
statistics_verbosity_level: low # off, low, high

# ------------ Subscribe to localizer space monitor -----------

# Subscribe to localizer space monitor
b_sub_to_lsm: false
xy_cross_section_threshold: 2500 # m^2
b_publish_xy_cross_section: true
# Closed space keyframe policy
translation_threshold_closed_space_kf: 1.0
rotation_threshold_closed_space_kf: 0.3
# Open space keyframe policy
translation_threshold_open_space_kf: 2.0
rotation_threshold_open_space_kf: 0.6

# -------------------Adaptive voxelization---------------------

b_adaptive_input_voxelization: true
points_to_process_in_callback: 3000

# ------------- Debug utilities -------------------------------

b_debug_transforms: false
wait_for_odom_transform_timeout: 0.1

# ------------------- Dynamic Switching -----------------------

sensor_health_timeout: 0.4
